# Generated by Django 3.2.7 on 2023-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clas',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'школа', 'verbose_name_plural': 'школы'},
        ),
        migrations.AddField(
            model_name='clas',
            name='student_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
