# Generated by Django 3.2.7 on 2023-04-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.clas'),
        ),
    ]
